//
// Created by klara on 23.07.24.
//

#ifndef INITIAL_VIEW_SELECTION_FOR_NOVEL_VIEW_RENDERING_SOLVELARGE_H
#define INITIAL_VIEW_SELECTION_FOR_NOVEL_VIEW_RENDERING_SOLVELARGE_H


class SolveLarge {

};


#endif //INITIAL_VIEW_SELECTION_FOR_NOVEL_VIEW_RENDERING_SOLVELARGE_H
